baseurl = "//ankushKun.github.io"
languageCode = "en-us"
theme = "terminal"

authorName = "Ankush Singh"
paginate = 5

[params]
  themeColor = "orange"
  contentTypeName = ""
  centerTheme = true
  showLastUpdated = true
  updateDatePrefix = "Last Updated On"
  readingTime = true
  custom_css = ["static/css/custom.css"]

[markup.goldmark.renderer]
  unsafe = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Ankush Singhs blog"
    subtitle = "A simple blog existing on Github pages"
    owner = "Ankush Singh"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "AS"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
